myEmptyNumberList = []

number1 = input("number1: ")
number2 = input("number2: ")
number3 = input("number3: ")
number4 = input("number4: ")
number5 = input("number5: ")
number6 = input("number6: ")
number7 = input("number7: ")
number8 = input("number8: ")
number9 = input("number9: ")
number10 = input("number10: ")

myEmptyNumberList.append(number1)
myEmptyNumberList.append(number2)
myEmptyNumberList.append(number3)
myEmptyNumberList.append(number4)
myEmptyNumberList.append(number5)
myEmptyNumberList.append(number6)
myEmptyNumberList.append(number7)
myEmptyNumberList.append(number8)
myEmptyNumberList.append(number9)
myEmptyNumberList.append(number10)
print(myEmptyNumberList)